// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
            <SectionErrorBoundary name="contact">
              <ContactCta
        tag="ARIES"
        text="THE BUILDING DOESN’T EXIST YET. YOUR EXPERIENCE OF IT CAN. SEE IT BEFORE IT EXISTS."
        primaryButton={{"href":"#","text":"START YOUR PROJECT ↗"}}
        secondaryButton={{"href":"#platform","text":"EXPLORE ARIES ↗"}}
        textAnimation="fade-blur"
      />
            </SectionErrorBoundary>
          </div>
  );
}
