// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
            <SectionErrorBoundary name="contact">
              <ContactCta
                tag="Start Building"
                text="DON’T JUST IMAGINE IT. EXPERIENCE IT. Build what doesn’t exist yet — with ARIES."
                primaryButton={{ text: "Get Started", href: "#" }}
                secondaryButton={{ text: "View Samples", href: "#" }}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
