// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
            <SectionErrorBoundary name="faq">
              <FaqSimple
                tag="Support"
                title="Frequently Asked Questions"
                description="Everything you need to know about ARIES."
                items={[
                  { question: "What files does ARIES support?", answer: "We support blueprints, sketches, CAD, and various image formats." },
                  { question: "Can I request revisions?", answer: "Yes, our interactive revision engine is built for feedback." },
                  { question: "Is the system secure?", answer: "Security is our top priority, ensuring project intellectual property stays protected." }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
