// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardTiltedCarousel from '@/components/sections/hero/HeroBillboardTiltedCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
            <SectionErrorBoundary name="hero">
              <HeroBillboardTiltedCarousel
                tag="Next-Generation Rendering"
                title="SEE IT BEFORE IT EXISTS."
                description="From plans to photorealistic experiences. Powered by ARIES."
                primaryButton={{
                  text: "Start a Project ↗",
                  href: "#contact"
                }}
                secondaryButton={{
                  text: "Explore ARIES ↗",
                  href: "#platform"
                }}
                items={[
                  { imageSrc: "http://img.b2bpic.net/free-photo/design-house-modern-villa-with-open-plan-living-private-bedroom-wing-large-terrace-with-privacy_1258-169747.jpg" },
                  { imageSrc: "http://img.b2bpic.net/free-photo/3d-rendering-abstract-building_23-2150896916.jpg" },
                  { imageSrc: "http://img.b2bpic.net/free-photo/photorealistic-wooden-house-with-timber-structure_23-2151302680.jpg" },
                  { imageSrc: "http://img.b2bpic.net/free-photo/luxurious-villa-with-modern-architectural-design_23-2151694045.jpg" },
                  { imageSrc: "http://img.b2bpic.net/free-photo/cliffside-modern-home-with-infinity-pool_23-2152008225.jpg" },
                  { imageSrc: "http://img.b2bpic.net/free-photo/3d-house-model-with-modern-architecture_23-2151004028.jpg" }
                ]}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
