/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import TiltedCarousel from "@/components/ui/TiltedCarousel";

const primaryButton = {
  text: "Start a Project ↗",
  href: "#contact"
};
const secondaryButton = {
  text: "Explore ARIES ↗",
  href: "#platform"
};
const items = [
  {
    imageSrc: "http://img.b2bpic.net/free-photo/design-house-modern-villa-with-open-plan-living-private-bedroom-wing-large-terrace-with-privacy_1258-169747.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/3d-rendering-abstract-building_23-2150896916.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/photorealistic-wooden-house-with-timber-structure_23-2151302680.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/luxurious-villa-with-modern-architectural-design_23-2151694045.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/cliffside-modern-home-with-infinity-pool_23-2152008225.jpg"
  },
  {
    imageSrc: "http://img.b2bpic.net/free-photo/3d-house-model-with-modern-architecture_23-2151004028.jpg"
  }
];

type HeroBillboardTiltedCarouselProps = {
  tag: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  items: ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never })[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
};

const HeroInline = () => {
  return (
    <section
      aria-label="Hero section"
      className="relative flex flex-col items-center justify-between w-full min-h-screen pt-24 pb-12 overflow-hidden bg-[#030712]"
    >
      <div className="absolute inset-0 z-0">
        <img
          src="http://img.b2bpic.net/free-photo/design-house-modern-villa-with-open-plan-living-private-bedroom-wing-large-terrace-with-privacy_1258-169747.jpg"
          alt="ARIES Architecture Rendering"
          className="w-full h-full object-cover object-center brightness-[0.7] contrast-[1.05]"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/20 to-[#030712]" />
      </div>

      <div className="relative z-10 flex items-center justify-between w-full px-6 md:px-12 max-w-7xl mx-auto">
        <div className="px-4 py-1.5 rounded-full bg-white/10 backdrop-blur-md border border-white/15 text-xs tracking-[0.2em] font-mono text-white/80">
          ARIES // ARCHITECTURE RENDERING INTELLIGENCE SYSTEM
        </div>
        <a href="#contact" className="hidden sm:inline-block px-5 py-2 rounded-full bg-white text-black font-medium text-xs tracking-wider uppercase hover:bg-cyan-400 transition-colors">
          Start Project
        </a>
      </div>

      <div className="relative z-10 flex flex-col items-center text-center gap-4 px-4 my-auto">
        <h1 className="text-7xl sm:text-9xl md:text-[12rem] font-extrabold tracking-tighter text-white uppercase leading-none drop-shadow-2xl">
          ARIES
        </h1>
        <p className="text-lg sm:text-2xl md:text-3xl font-light tracking-[0.25em] text-white/90 uppercase max-w-3xl">
          SEE IT BEFORE IT EXISTS.
        </p>
        <div className="flex flex-wrap justify-center gap-4 mt-6">
          <Button text="Start a Project ↗" href="#contact" variant="primary"/>
          <Button text="Explore System ↗" href="#platform" variant="secondary"/>
        </div>
      </div>

      <div className="relative z-10 flex items-center gap-3 text-xs font-mono uppercase text-white/60 tracking-widest">
        <span className="w-8 h-[1px] bg-white/40 animate-pulse" />
        <span>Architectural Technology Experience</span>
      </div>
    </section>
  );
};

export default function HeroSection() {
  return (
    <div data-webild-section="hero" data-section="hero" id="hero">
      <HeroInline />
    </div>
  );
}
