// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
            <SectionErrorBoundary name="metrics">
              <MetricsMediaCards
                tag="Innovation"
                title="Design Precision, AI Powered"
                description="ARIES sets the new standard for professional architectural visualization."
                metrics={[
                  { value: "100%", title: "Photorealism", description: "Achieve stunning visual accuracy every time.", imageSrc: "http://img.b2bpic.net/free-photo/3d-model-house-room_23-2150761110.jpg" },
                  { value: "10x", title: "Speed", description: "Visualize projects in a fraction of the time.", imageSrc: "http://img.b2bpic.net/free-photo/3d-rendering-abstract-building_23-2150896640.jpg" }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
