// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "platform" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PlatformSection(): React.JSX.Element {
  return (
    <div id="platform" data-section="platform">
            <SectionErrorBoundary name="platform">
              <FeaturesRevealCardsBento
                tag="The System"
                title="ARIES Platform Capabilities"
                description="Transform your design workflow into an experience."
                items={[
                  { title: "AI Rendering", description: "Turn plans into photorealistic imagery.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/modern-office-space-with-futuristic-decor-furniture_23-2151797639.jpg" },
                  { title: "Interior Viz", description: "High-fidelity interior visualization.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/brutalist-inspiration-architecture-background_23-2149162901.jpg" },
                  { title: "Exterior Viz", description: "Generate realistic outdoor settings.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/photorealistic-timber-house-interior-with-wooden-decor-furnishings_23-2151263586.jpg" },
                  { title: "Interactive", description: "Real-time design exploration tools.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/top-view-tablet-top-architectural-plan_23-2148269855.jpg" },
                  { title: "360° Experiences", description: "Immersive virtual environments.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/building-with-colorful-walls_1127-2241.jpg" },
                  { title: "Dashboard", description: "Professional project management.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/top-view-laptop-table-glowing-screen-dark_169016-53642.jpg" },
                  { title: "Collaboration", description: "Seamless professional integration.", href: "#", imageSrc: "http://img.b2bpic.net/free-photo/blueprint-architect-construction-project-sketch-concept_53876-133820.jpg" }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
