// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "solutions" section.

import React from 'react';
import PricingCenteredCards from '@/components/sections/pricing/PricingCenteredCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SolutionsSection(): React.JSX.Element {
  return (
    <div id="solutions" data-section="solutions">
            <SectionErrorBoundary name="solutions">
              <PricingCenteredCards
                tag="Professional Solutions"
                title="Plans for Every Professional"
                description="Tailored solutions for your specific design needs."
                plans={[
                  { tag: "Architects", price: "Custom", description: "Professional toolset for large firm projects.", features: ["Advanced Material Editing", "Team Collaboration", "Cloud Rendering"], primaryButton: { text: "Contact Sales", href: "#contact" } },
                  { tag: "Developers", price: "Custom", description: "Scale development visualization effortlessly.", features: ["Bulk Image Generation", "API Integration", "Priority Scaling"], primaryButton: { text: "Contact Sales", href: "#contact" } }
                ]}
                textAnimation="slide-up"
              />
            </SectionErrorBoundary>
          </div>
  );
}
