// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialRatingCards from '@/components/sections/testimonial/TestimonialRatingCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
            <SectionErrorBoundary name="testimonials">
              <TestimonialRatingCards
                tag="Trust"
                title="Trusted by Visionaries"
                description="The industry standard for architectural visualization."
                testimonials={[
                  { name: "Elena Rossi", role: "Architect", quote: "ARIES transformed our client meetings entirely.", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/handsome-confident-man_1098-18449.jpg" },
                  { name: "Marcus Chen", role: "Developer", quote: "The speed and quality are unprecedented.", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/portrait-pretty-young-woman-working-blueprint-working-place_23-2148203942.jpg" },
                  { name: "Sophia Moore", role: "Interior Designer", quote: "I can explore endless finishes in seconds.", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-woman-working-interior-design-project_23-2150346546.jpg" },
                  { name: "James Wilson", role: "Project Manager", quote: "Unbeatable accuracy for modern developments.", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-man-holding-clipboard_23-2148921393.jpg" },
                  { name: "Dr. Sarah Lee", role: "Lead Architect", quote: "The visualization engine is world-class.", rating: 5, imageSrc: "http://img.b2bpic.net/free-photo/portrait-confident-young-male-engineer-against-white-backdrop_23-2147843008.jpg" }
                ]}
                textAnimation="fade-blur"
              />
            </SectionErrorBoundary>
          </div>
  );
}
